// <auto-generated />
using System;
using EntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20230718231059_BaseEntityCreated")]
    partial class BaseEntityCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticleTable", b =>
                {
                    b.Property<int>("ArticlesID")
                        .HasColumnType("int");

                    b.Property<int>("TablesID")
                        .HasColumnType("int");

                    b.HasKey("ArticlesID", "TablesID");

                    b.HasIndex("TablesID");

                    b.ToTable("ArticleTable");
                });

            modelBuilder.Entity("EntityFramework.Models.BaseEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("BaseEntities");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EntityFramework.Models.Article", b =>
                {
                    b.HasBaseType("EntityFramework.Models.BaseEntity");

                    b.Property<long>("Barcode")
                        .HasColumnType("bigint");

                    b.Property<int?>("BillID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DispatchNoteID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasIndex("BillID");

                    b.HasIndex("DispatchNoteID");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("Quantity")
                                .HasColumnName("Article_Quantity");
                        });

                    b.HasDiscriminator().HasValue("Article");
                });

            modelBuilder.Entity("EntityFramework.Models.ArticleDetails", b =>
                {
                    b.HasBaseType("EntityFramework.Models.BaseEntity");

                    b.Property<int?>("ArticleID")
                        .HasColumnType("int");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasIndex("ArticleID");

                    b.HasDiscriminator().HasValue("ArticleDetails");
                });

            modelBuilder.Entity("EntityFramework.Models.Bill", b =>
                {
                    b.HasBaseType("EntityFramework.Models.BaseEntity");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Bill");
                });

            modelBuilder.Entity("EntityFramework.Models.DispatchNote", b =>
                {
                    b.HasBaseType("EntityFramework.Models.BaseEntity");

                    b.Property<int>("DispatchNoteNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("DispatchNote");
                });

            modelBuilder.Entity("EntityFramework.Models.Table", b =>
                {
                    b.HasBaseType("EntityFramework.Models.BaseEntity");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int?>("BillID")
                        .HasColumnType("int");

                    b.HasIndex("BillID");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("BillID")
                                .HasColumnName("Table_BillID");
                        });

                    b.HasDiscriminator().HasValue("Table");
                });

            modelBuilder.Entity("EntityFramework.Models.Waiter", b =>
                {
                    b.HasBaseType("EntityFramework.Models.BaseEntity");

                    b.Property<long>("Barcode")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstAndLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("JMBG")
                        .HasColumnType("bigint");

                    b.ToTable("BaseEntities", t =>
                        {
                            t.Property("Barcode")
                                .HasColumnName("Waiter_Barcode");
                        });

                    b.HasDiscriminator().HasValue("Waiter");
                });

            modelBuilder.Entity("ArticleTable", b =>
                {
                    b.HasOne("EntityFramework.Models.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticlesID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.Table", null)
                        .WithMany()
                        .HasForeignKey("TablesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFramework.Models.Article", b =>
                {
                    b.HasOne("EntityFramework.Models.Bill", null)
                        .WithMany("BoughtArticles")
                        .HasForeignKey("BillID");

                    b.HasOne("EntityFramework.Models.DispatchNote", null)
                        .WithMany("Articles")
                        .HasForeignKey("DispatchNoteID");
                });

            modelBuilder.Entity("EntityFramework.Models.ArticleDetails", b =>
                {
                    b.HasOne("EntityFramework.Models.Article", "Article")
                        .WithMany("ArticleDetails")
                        .HasForeignKey("ArticleID");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("EntityFramework.Models.Table", b =>
                {
                    b.HasOne("EntityFramework.Models.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillID");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("EntityFramework.Models.Article", b =>
                {
                    b.Navigation("ArticleDetails");
                });

            modelBuilder.Entity("EntityFramework.Models.Bill", b =>
                {
                    b.Navigation("BoughtArticles");
                });

            modelBuilder.Entity("EntityFramework.Models.DispatchNote", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
